clavem:
  hosts:
    mydsagenthost:

teddy_salad:
  hosts:
    mydsagenthost:

dsagent:
  children:
    teddy_salad:
    clavem:

scheduler:
  hosts:
    myschedulerhost:

scanner:
  hosts:
#    myscannerhost1:
#    myscannerhost2:

hiab:
  children:
    scheduler:
    scanner:
